#!/usr/bin/env bash
# Reads number from file and print their factors in file

FILE=$1

while read NUM
do
    factors=($(factor $NUM))
    echo "$NUM=$(($NUM/${factors[1]}))*${factors[1]}"
done < $FILE